services:
  python:
    image: python:3.12-alpine
    profiles: ["python"]
    container_name: python_env
    stdin_open: true
    tty: true
    command: sleep infinity
    volumes:
      - ./workspace:/workspace

  rust:
    image: rust:alpine
    profiles: ["rust"]
    container_name: rust_env
    stdin_open: true
    tty: true
    command: sleep infinity
    volumes:
      - ./workspace:/workspace

  go:
    image: golang:alpine
    profiles: ["go"]
    container_name: go_env
    stdin_open: true
    tty: true
    command: sleep infinity
    volumes:
      - ./workspace:/workspace

  bun:
    image: oven/bun:alpine
    profiles: ["go"]
    container_name: bun_env
    stdin_open: true
    tty: true
    command: sleep infinity
    volumes:
      - ./workspace:/workspace
